pipeline:
  name: test-pipeline
  identifier: testpipeline
  projectIdentifier: Infra
  orgIdentifier: default
  description: First Pipeline
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: raviconnector
        build: <+input>
  stages:
    - stage:
        name: Pre-check
        identifier: Precheck
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.danfstatestcluster
              namespace: harness-delegate-ng-statest
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: "test "
                  identifier: test
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.5.2-jdk-8-alpine
                    shell: Bash
                    command: |-
                      #!/bin/bash

                      echo "Test"
        when:
          pipelineStatus: All
    - stage:
        name: Trivy
        identifier: Trivy
        description: Run Trivy Scan
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            useFromStage: Precheck
          execution:
            steps:
              - step:
                  type: Run
                  name: Trivy
                  identifier: Trivy
                  spec:
                    connectorRef: account.harnessImage
                    image: aquasec/trivy:latest
                    shell: Sh
                    command: |-
                      #!/bin/sh

                      trivy config --severity HIGH,CRITICAL --exit-code 1 ./aws/ec2/examples
                  description: Run Trivy Scan on Repo
                  failureStrategies: []
